# Generated by Django 5.1.1 on 2024-09-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='foto',
        ),
        migrations.AlterField(
            model_name='empresas',
            name='logo',
            field=models.ImageField(null=True, upload_to='imagemEmpresa'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email '),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome '),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=20, verbose_name='Senha '),
        ),
    ]
