# Generated by Django 5.1.1 on 2024-09-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_remove_usuario_foto_alter_empresas_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresas',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='foto',
        ),
        migrations.AlterField(
            model_name='jogo',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=20),
        ),
    ]
